services:
  - mssql2017

install:
  - npm install

build_script:
  - ps: .\test\appveyor-mssql.ps1
  - npm run build
  - npm link
  - ssc pull -c ./test/appveyor-config.json

test_script:
  - node ./test/appveyor-test.js
